convert path to url to fix windows support
PrismarineJS/mineflayer-test-api pull request #12
Opened 2021-04-13 04:16 UTC by u9g

2021-04-13 13:19 UTC, u9g commented
should I add windows tests for this to ensure this continues to work?

2021-04-13 14:57 UTC, TheDudeFromCI commented
> should I add windows tests for this to ensure this continues to work?

Yeah, go for it. Should be easy to modify the ci.yml

2021-04-14 12:49 UTC, TheDudeFromCI requested changes

2021-04-14 12:49 UTC, TheDudeFromCI commented on .github/workflows/ci.yml
> +    - run: npm run lint
We should probably run the test on both OSs, just to be sure.

2021-04-14 16:00 UTC, TheDudeFromCI approved these changes

2021-04-14 16:01 UTC, merged